name = "DataFrameTools"
uuid = "2e886b56-b55e-403a-a2d0-ccbf75d993da"
authors = ["Tsung-Hsi Wu <okatsn@gmail.com>"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
MAT = "23992714-dd62-5051-b70f-ba57cb901cac"

[compat]
DataFrames = "1"
julia = "1.6.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
